config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :consumers, only: [:index, :show] do
    resources :snacks, only: [:index]
  end

  resources :brands, only: [:index, :show] do
    resources :snacks, only: [:index]
  end

  resources :snacks, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :snacks
  has_many :consumers, through: :snacks
end

app/models/consumer.rb
class Consumer < ApplicationRecord
  has_many :consumerships
  has_many :snacks, through: :consumerships
end

app/models/consumership.rb
class Consumership < ApplicationRecord
  belongs_to :consumer
  belongs_to :snack
end

app/models/snack.rb
class Snack < ApplicationRecord
  belongs_to :brand

  has_many :consumerships
  has_many :consumers, through: :consumerships
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  def index
    @brands = Brand.all
  end

  def show
    @brand = Brand.find(params[:id])
  end
end

app/controllers/consumers_controller.rb
class ConsumersController < ApplicationController
  def index
    @consumers = Consumer.all

    # the line below is implicit
    # render :index
  end

  def show
    @consumer = Consumer.find(params[:id])

    # the line below is implicit
    # render :show
  end
end

app/controllers/snacks_controller.rb
class SnacksController < ApplicationController

  def index
    if params[:consumer_id]
      @consumer = Consumer.find(params[:consumer_id])
      @snacks = @consumer.snacks
    elsif params[:brand_id]
      @brand = Brand.find(params[:brand_id])
      @snacks = @brand.snacks
    else
      @snacks = Snack.all
    end
  end

  def show
    @snack = Snack.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/consumers_helper.rb
module ConsumersHelper
end

app/helpers/snacks_helper.rb
module SnacksHelper
end

app/views/brands/index.html.erb
<h2>Brands</h2>

<ul>
  <% @brands.each do |brand| %>
    <li>
      <%= link_to brand.name, brand_path(brand) %>
    </li>
  <% end %>
</ul>

app/views/brands/show.html.erb
<h3><%= @brand.name %></h3>

<%= image_tag @brand.logo %>

<br>

<%= link_to "#{@brand.name}'s snacks", brand_snacks_path(@brand) %>
|
<%= link_to "Consumers", consumers_path %>

app/views/consumers/index.html.erb
<h2>Consumers</h2>

<ul>
  <% @consumers.each do |consumer| %>
    <li>
      <%= link_to consumer.name, consumer_path(consumer) %>
    </li>
  <% end %>
</ul>

app/views/consumers/show.html.erb
<h3><%= @consumer.name %></h3>

<div class="consumer-info">

  <%= @consumer.name %> is <%= @consumer.age %> years old

</div>

<br>

<%= link_to "#{@consumer.name}'s snacks", consumer_snacks_path(@consumer) %>
|
<%= link_to "Consumers", consumers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SnackAttack</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <center><b><i><u> <!-- fun html tags !! bring back the 90s!! -->
      Snack Attack!
    </u></i></b></center>

    <%= yield %>

    <hr>

    <div class="index-links">
      <%= link_to "Consumers", consumers_path %>
      |
      <%= link_to "Brands", brands_path %>
      |
      <%= link_to "Snacks", snacks_path %>
    </div>

  </body>


</html>

app/views/snacks/index.html.erb
<h2>
  <%= @consumer.try(:name) || @brand.try(:name) || 'All' %> Snacks
</h2>

<ul>
  <% if @snacks.empty? %>

    No snacks :(

  <% else %>

    <% @snacks.each do |snack| %>
      <li>
        <%= link_to snack.name, snack_path(snack) %>
      </li>
    <% end %>

  <% end %>
</ul>

app/views/snacks/show.html.erb
<h2><%= @snack.name %></h2>

calories: <%= @snack.calories %>